### ISSUE TITLE
[REFACTOR] Remove the MutationObserver code

### ISSUE THREAD

**Issue by csouchet** [process-analytics/icpm-demo-2022#33]
Initial request: "add function to configure containerObserver"

**Comment by tbouffard** [comment]
Can you provide more details in the description?
In my mind, we should remove the `MutationObserver` which is currently useless and fix #2 and #24 

https://github.com/assynour/icpm-demo-2022/blob/aef4e01609ccd557a5e8fd615fd4112889ae3e47/src/index.js#L38-L58
